import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  getCaseById,
  getCustomerById,
  getOrderById,
  updateCase,
  appendAudit,
} from "@/lib/db/queries";
import { requireAuth } from "@/lib/auth/session";
import { draftResponse } from "@/lib/ai/responder";
import { getSettings } from "@/lib/db/queries";
import type { AIClassification } from "@/types";

export const runtime = "nodejs";

const schema = z.object({
  caseId: z.string().min(1),
  customInstructions: z.string().max(1000).optional(),
});

export async function POST(req: NextRequest) {
  let user;
  try {
    user = await requireAuth();
  } catch (err) {
    const e = err as Error & { status?: number };
    return NextResponse.json({ error: e.message }, { status: e.status ?? 401 });
  }

  const body = await req.json().catch(() => null);
  const parsed = schema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", details: parsed.error.flatten() },
      { status: 400 }
    );
  }
  const { caseId, customInstructions } = parsed.data;

  const c = await getCaseById(caseId);
  if (!c) return NextResponse.json({ error: "Case not found" }, { status: 404 });
  if (!c.intent) return NextResponse.json({ error: "Case must be classified first" }, { status: 400 });

  const customer = await getCustomerById(c.customerId);
  if (!customer) return NextResponse.json({ error: "Customer not found" }, { status: 404 });
  const order = c.orderId ? await getOrderById(c.orderId) : undefined;
  const settings = await getSettings();

  const classification: AIClassification = {
    intent: c.intent,
    sentiment: c.sentiment ?? "neutral",
    sentimentScore: c.sentimentScore ?? 0,
    urgency: c.urgency ?? "medium",
    confidence: c.confidence ?? 0.5,
    automationSafe: c.automationSafe ?? true,
    neededContext: [],
    explanation: "",
    keywords: [],
  };

  const plan = c.resolutionPlan ?? {
    goal: `Resolve ${c.intent.replace(/_/g, " ")} for ${customer.name}.`,
    approach: "Agent-initiated resolution.",
    workflowSteps: c.workflowSteps ?? [],
    estimatedResolutionMins: 5,
    customerImpact: "Customer will receive a personalized response.",
    risksIdentified: [],
  };

  const draft = await draftResponse(classification, customer, order, plan);
  const finalDraft = customInstructions
    ? `${draft}\n\n— Additional note from our team: ${customInstructions}`
    : draft;

  const updated = await updateCase(c.id, {
    responseDraft: finalDraft,
  });

  await appendAudit({
    caseId: c.id,
    customerId: customer.id,
    actorId: user.id,
    actorType: c.responseDraft ? "agent" : "ai",
    action: "response.regenerate",
    category: "action",
    detail: c.responseDraft
      ? `Response draft regenerated by ${user.name}${customInstructions ? ` with custom instructions` : ""}.`
      : `Response draft generated by AI${customInstructions ? ` with agent instructions` : ""}.`,
    metadata: { tone: settings.responseTone, customInstructions: !!customInstructions },
  });

  return NextResponse.json({ case: updated, draft: finalDraft });
}
